### ISSUE TITLE
Suggestion: Heightmap models and collisions and texturemaps

### ISSUE THREAD

**Issue by ShadowLordAlpha** [sriharshachilakapati/SilenceEngine#12] opened 2015-04-27 17:58 UTC
Heightmap - A grayscale image that is used to generate a model that is normally used as the ground in a 3D game.

Texturemap - Same size of the Heightmap image that is colored and each color channel (RGBA) represents a different texture to be painted onto the model allows mixing of textures because what texture is where is based on the color of the pixel at that point

In addition a Collision should also be generated from the Heightmap file as most of the time a heightmaps use is limited to the ground.

**Comment by ShadowLordAlpha** [comment] 2015-04-27 17:59
probably could have thought of a better way to word that

**Comment by sriharshachilakapati** [comment] 2015-04-28 02:57
SilenceEngine, as it stands right now, is in a pre-mature state, and there are bugs (identified) in the core features like the SceneGraph. This will be done in 0.0.4a, as the primary goal of 0.0.3a is to provide Object Oriented Abstractions to the native libraries that LWJGL provides bindings to, making SilenceEngine easier to use than LWJGL, and at the same time, is as flexible as you can with pure LWJGL.

What you suggested is actually very good, I will have it implemented by the end of 0.0.4a release. The problem is, I had a lot of work on myself (very less contributors) so I had been giving first priority to the release of 0.0.3a with complete documentation. Just wanted to say what is happening here. It would be great if you could contribute, I will give proper credits for your work.

**Comment by ShadowLordAlpha** [comment] 2015-04-28 03:31
I'm putting things down as suggestions here because I forget things and am more experimenting with the engine atm. Also I was assuming that you wanted to get 0.0.3a fully ready and out before things that you have marked for 0.0.4a were started on

**Comment by sriharshachilakapati** [comment] 2015-04-28 03:37
Your assumption is right, but the new scene graph is also marked for the 0.0.4a release. And there is nothing wrong in suggesting features, I do require suggestions. I just wanted to let you know the current state of the engine, and my plans for this release.

**Comment by sriharshachilakapati** [comment] 2015-10-25 15:22
Closing this now as it is getting late for a new release. Will reopen them with a new milestone after release.

**Closed by sriharshachilakapati** 2015-10-25 15:22 UTC
Labels: enhancement
